/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package imagesteganographyrle;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import jnafilechooser.api.JnaFileChooser;

/**
 *
 * @author ADMIN
 */
public class Home extends javax.swing.JFrame {
    static int numberOfChar = 0;
    static BufferedImage tmp;
    static String extension = "";
    static String fileName = "";
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/hide.png")));
        setTitle("SteganoRLE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_imagepath = new javax.swing.JLabel();
        jButton_Browse = new javax.swing.JButton();
        jTextField_pathImage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_message = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton_clearMessage = new javax.swing.JButton();
        jButton_saveMessage = new javax.swing.JButton();
        jButton_copyMessage = new javax.swing.JButton();
        jCheckBox_show_password = new javax.swing.JCheckBox();
        jPasswordField_passwd = new javax.swing.JPasswordField();
        jLabel_numberofchar = new javax.swing.JLabel();
        jButton_load = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton_Embed = new javax.swing.JRadioButton();
        jRadioButton_Extract = new javax.swing.JRadioButton();
        jButton_About = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jButton_Start = new javax.swing.JButton();
        jButton_open_file_location = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel_image_input = new javax.swing.JLabel();
        jLabel_output_image = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));

        jPanel3.setBackground(new java.awt.Color(240, 240, 240));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Specify image, message, key for process", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel_imagepath.setText("Image:");

        jButton_Browse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-image (3).png"))); // NOI18N
        jButton_Browse.setText("Browse");
        jButton_Browse.setToolTipText("");
        jButton_Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BrowseActionPerformed(evt);
            }
        });

        jTextField_pathImage.setEditable(false);

        jLabel2.setText("Message:");

        jTextArea_message.setColumns(20);
        jTextArea_message.setRows(5);
        jScrollPane1.setViewportView(jTextArea_message);

        jLabel4.setText("Password (may be blank):");

        jButton_clearMessage.setText("Clear");
        jButton_clearMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearMessageActionPerformed(evt);
            }
        });

        jButton_saveMessage.setText("Save");
        jButton_saveMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveMessageActionPerformed(evt);
            }
        });

        jButton_copyMessage.setText("Copy");
        jButton_copyMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_copyMessageActionPerformed(evt);
            }
        });

        jCheckBox_show_password.setText("Show");
        jCheckBox_show_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_show_passwordActionPerformed(evt);
            }
        });

        jLabel_numberofchar.setForeground(new java.awt.Color(255, 51, 51));

        jButton_load.setText("Load");
        jButton_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel_imagepath)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel_numberofchar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jPasswordField_passwd, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_pathImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBox_show_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_Browse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_clearMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_copyMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_saveMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_imagepath)
                    .addComponent(jLabel_numberofchar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Browse)
                    .addComponent(jTextField_pathImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCheckBox_show_password)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPasswordField_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton_load)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_clearMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_copyMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_saveMessage)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Steganography Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel3.setText("Choose Mode:");

        buttonGroup1.add(jRadioButton_Embed);
        jRadioButton_Embed.setSelected(true);
        jRadioButton_Embed.setText("Embed");
        jRadioButton_Embed.setToolTipText("");
        jRadioButton_Embed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_EmbedActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_Extract);
        jRadioButton_Extract.setText("Extract");
        jRadioButton_Extract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_ExtractActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addComponent(jRadioButton_Embed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_Extract, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton_Embed)
                    .addComponent(jRadioButton_Extract))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jButton_About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/information.png"))); // NOI18N
        jButton_About.setText("About");
        jButton_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AboutActionPerformed(evt);
            }
        });

        jButton_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete-button.png"))); // NOI18N
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jButton_Start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/power.png"))); // NOI18N
        jButton_Start.setText("Start");
        jButton_Start.setToolTipText("");
        jButton_Start.setEnabled(false);
        jButton_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StartActionPerformed(evt);
            }
        });

        jButton_open_file_location.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/saveim.png"))); // NOI18N
        jButton_open_file_location.setText("Save Image");
        jButton_open_file_location.setEnabled(false);
        jButton_open_file_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_open_file_locationActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(240, 240, 240));

        jLabel_image_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_output_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Image Input:");

        jLabel7.setText("Image Output:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_output_image, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_image_input, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addComponent(jLabel_image_input, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_output_image, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton_open_file_location)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Cancel)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_About, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_About)
                        .addComponent(jButton_Cancel)
                        .addComponent(jButton_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_open_file_location))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_About, jButton_Cancel, jButton_Start, jButton_open_file_location});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton_clearMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearMessageActionPerformed
        // TODO add your handling code here:
        jTextArea_message.setText("");
    }//GEN-LAST:event_jButton_clearMessageActionPerformed

    private void jButton_saveMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveMessageActionPerformed
        // TODO add your handling code here:
        JnaFileChooser fileChooser = new JnaFileChooser();
        fileChooser.setMode(JnaFileChooser.Mode.Directories);
        //fileChooser.showSaveDialog(this);
        
        boolean action = fileChooser.showOpenDialog(this);
        if(action){
            File f = fileChooser.getSelectedFile();
            try {
                //FileWriter fw = new FileWriter(new File(f.getAbsolutePath() + "\\message.txt"));
                String text = jTextArea_message.getText();
                //fw.write(text);
                //fw.close();
                BufferedWriter wr = Files.newBufferedWriter(Paths.get(f.getAbsolutePath() + "\\message.txt"), StandardCharsets.UTF_8);
                wr.write(text);
                wr.close();
            } catch (Exception e) {
            }
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/image/accept.png"));
            JOptionPane.showMessageDialog(this, "Saved!", "Notify", JOptionPane.INFORMATION_MESSAGE, icon);
        }
            
    }//GEN-LAST:event_jButton_saveMessageActionPerformed

    private void jCheckBox_show_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_show_passwordActionPerformed
        // TODO add your handling code here:
        if(jCheckBox_show_password.isSelected()){
            jPasswordField_passwd.setEchoChar((char)0);
        }else{
            jPasswordField_passwd.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox_show_passwordActionPerformed

    private void jButton_BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BrowseActionPerformed
        // TODO add your handling code here:
        //cach vip
        JnaFileChooser fileChooser = new JnaFileChooser();
        boolean action = fileChooser.showOpenDialog(this);
        if(action){
            File file = fileChooser.getSelectedFile();
            String pathFile = file.getAbsolutePath();
            int indexOFDot = pathFile.lastIndexOf(".");
            String ext = pathFile.substring(indexOFDot+1).toLowerCase();
            if("jpg, jpeg, png, bmp, tiff".contains(ext)){
                jTextField_pathImage.setText(pathFile);
                BufferedImage bf;
                try{
                    bf = ImageIO.read(new File(pathFile));
                    //tinh so ky tu co the giau trong anh
                    int[][] pixel = Steganography.getPixelMatrix(bf, bf.getWidth(), bf.getHeight());
                    numberOfChar = Steganography.caculateLenOfMessage(pixel);
                    //hien thi so ky tu
                    String stegaMode = jRadioButton_Embed.isSelected() ? "Embeb" : "Extract";
                    if(stegaMode.equals("Embeb")){
                        jLabel_numberofchar.setText("this image can hide " + numberOfChar + " characters");
                    }
                    //set input image
                    ImageIcon icon = new ImageIcon(bf);
                    Image img = icon.getImage();
                    Image imgScale = img.getScaledInstance(jLabel_image_input.getWidth(), jLabel_image_input.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon scaleIcon = new ImageIcon(imgScale);
                    jLabel_image_input.setIcon(scaleIcon);
                    //loai bo anh cu
                    jLabel_output_image.setIcon(null);
                    jButton_open_file_location.setEnabled(false);
                    
                    fileName = pathFile.substring(pathFile.lastIndexOf("\\")+1);
                    extension = ext;
                }catch(Exception e){
                    //show dialog neu hien thi anh loi
                    System.out.println("chon anh ban oi");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Only supports jpg, jpeg, png, bmp, tiff images!");
            }
        }
        if(jTextField_pathImage.getText().length() > 0){
            jButton_Start.setEnabled(true);
        }else{
            jButton_Start.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_jButton_BrowseActionPerformed

    private void jButton_copyMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_copyMessageActionPerformed
        // TODO add your handling code here:
        String text = jTextArea_message.getText();
        Clipboard clip = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection strselect = new StringSelection(text);
        clip.setContents(strselect, strselect);
    }//GEN-LAST:event_jButton_copyMessageActionPerformed

    private void jButton_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StartActionPerformed
        // TODO add your handling code here:
        //read image
        String pathImage = jTextField_pathImage.getText();
        BufferedImage orgImage = null;
        File f = null;
        try{
            f = new File(pathImage);
            orgImage = ImageIO.read(f);
        }catch(IOException e){
            System.out.println(e);
        }
        //get pass
        String password = String.copyValueOf(jPasswordField_passwd.getPassword());
        //get mode
        String stegaMode = jRadioButton_Embed.isSelected() ? "Embeb" : "Extract";
        
        if(stegaMode.equals("Embeb")){
            String message = jTextArea_message.getText().trim();
            
            if(message.equals("")){
                JOptionPane.showMessageDialog(this, "enter your message!");
            }
            else if(message.length()+1 > numberOfChar){
                JOptionPane.showMessageDialog(this, "the message is too long");
            }else{
                if(!password.equals("")){
                    message = AffineCipher.encrypt(message, password);
                }
                message += '\0';
                BufferedImage stegoImage = Steganography.Embed(orgImage, message);
                //set anh
                ImageIcon icon = new ImageIcon(stegoImage);
                Image img = icon.getImage();
                Image imgScale = img.getScaledInstance(jLabel_image_input.getWidth(), jLabel_image_input.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaleIcon = new ImageIcon(imgScale);
                jLabel_output_image.setIcon(scaleIcon);
                jButton_open_file_location.setEnabled(true);
                tmp = stegoImage;
                
            }
                
        }else if(stegaMode.equals("Extract")){
            String message = Steganography.Extract(orgImage);
            if(!password.equals("")){
                message = AffineCipher.decrypt(message, password);
            }
            jTextArea_message.setText(message);
        }
    }//GEN-LAST:event_jButton_StartActionPerformed

    private void jButton_open_file_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_open_file_locationActionPerformed
        JnaFileChooser fileChooser = new JnaFileChooser();
        fileChooser.setMode(JnaFileChooser.Mode.Directories);
        boolean action = fileChooser.showOpenDialog(this);
        if(action){
            File f = fileChooser.getSelectedFile();
            //write file
            try {
                File output = new File(f.getAbsolutePath() + "\\stego " + fileName);
                //System.out.println(extension);
                if("jpg jpeg".contains(extension)){
                    extension = "png";
                }
                
                ImageIO.write(tmp, extension, output);
                
            } catch (IOException ex) {

            }

            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/image/accept.png"));
            JOptionPane.showMessageDialog(this, "Saved!", "Notify", JOptionPane.INFORMATION_MESSAGE, icon);
        }
    }//GEN-LAST:event_jButton_open_file_locationActionPerformed

    private void jRadioButton_EmbedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_EmbedActionPerformed
        // TODO add your handling code here:
        if(numberOfChar > 0){
            jLabel_numberofchar.setText("this image can hide " + numberOfChar + " characters");
        }
    }//GEN-LAST:event_jRadioButton_EmbedActionPerformed

    private void jRadioButton_ExtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_ExtractActionPerformed
        // TODO add your handling code here:
        jLabel_numberofchar.setText("");
        jTextArea_message.setText("");
        jButton_open_file_location.setEnabled(false);
        jLabel_output_image.setIcon(null);
    }//GEN-LAST:event_jRadioButton_ExtractActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "SteganoRLE is a program to hide information in image using run-length encoding\n - Version: 1.0, Java SE 17, Apache NetBeans IDE 14\n - Developer: Tran Quoc Truong\n - Contact: trantruongac1@gmail.com", "About this app", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_AboutActionPerformed

    private void jButton_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loadActionPerformed
        // TODO add your handling code here:
        jTextArea_message.setText("");
        JnaFileChooser fileChooser = new JnaFileChooser();
        boolean action = fileChooser.showOpenDialog(this);
        if(action){
            File file = fileChooser.getSelectedFile();
            String pathFile = file.getAbsolutePath();
            int indexOFDot = pathFile.lastIndexOf(".");
            String ext = pathFile.substring(indexOFDot+1).toLowerCase();
            if(ext.equals("txt")){
                try {
                    //BufferedReader in = new BufferedReader(new FileReader(file), "UTF-8");
                    BufferedReader in = new BufferedReader(new InputStreamReader(new FileInputStream(file), "UTF-8"));
                    String line = in.readLine();
                    while(line != null){
                        jTextArea_message.append(line + "\n");
                        line = in.readLine();
                      }
                } catch (FileNotFoundException ex) {
                    
                } catch (IOException ex) {
                    //Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Please choose .txt file!");
            }
        }
    }//GEN-LAST:event_jButton_loadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_About;
    private javax.swing.JButton jButton_Browse;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Start;
    private javax.swing.JButton jButton_clearMessage;
    private javax.swing.JButton jButton_copyMessage;
    private javax.swing.JButton jButton_load;
    private javax.swing.JButton jButton_open_file_location;
    private javax.swing.JButton jButton_saveMessage;
    private javax.swing.JCheckBox jCheckBox_show_password;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_image_input;
    private javax.swing.JLabel jLabel_imagepath;
    private javax.swing.JLabel jLabel_numberofchar;
    private javax.swing.JLabel jLabel_output_image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField_passwd;
    private javax.swing.JRadioButton jRadioButton_Embed;
    private javax.swing.JRadioButton jRadioButton_Extract;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_message;
    private javax.swing.JTextField jTextField_pathImage;
    // End of variables declaration//GEN-END:variables
}
